name: main_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/onBoard.webp
    - assets/images/welcome.png
    - assets/images/goals.png
    - assets/images/insights.png
    - assets/images/budget.png
